name: gazejepa
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - scipy
  - opencv
  - matplotlib
  - pillow
  - scikit-learn
  - jupyter
  - tqdm
  - pyyaml
  - pandas
  - pip
  - pip:
    - einops
